---

# Commented out as a task file for deploy_container_local.yaml
#  hosts: localhost
#  tasks:
    - name: Check to see if brew is installed in default path of /usr/local/bin
      stat:
        path: /usr/local/bin/brew
      register: brew_exists

    - name: If brew isn't installed, install it
      shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      when: brew_exists.stat.exists == False

    ## RH CDK requires VirtualBox version 5.0.26
    - name: Install VirtualBox 5.0.26 via brew
      homebrew_cask:
        cask: virtualbox.rb
        state: present
        install_options: 'appdir=/Applications'
      ignore_errors: true


    ## RH CDK requires Vagrant version 1.8.0
    - name: Install Vagrant 1.8.0 via brew
      homebrew_cask:
        # When homebrew_cask supports URLs, use https://raw.githubusercontent.com/caskroom/homebrew-cask/8bd4de936e673cd895c106fce2a9d740007751fa/Casks/vagrant.rb
        cask: vagrant.rb
        state: present
      ignore_errors: true

    - name: Confirm that packages are present because homebrew_cask module doesn't handle local cask files or URLs appropriately
      stat:
        path: /usr/local/bin/'{{ item }}'
      with_items:
        - vagrant
        - virtualbox
      any_errors_fatal: true

    - name: Install OC package to connect Openshift instance
      homebrew:
        name: openshift-cli
        state: present
